### ISSUE TITLE
[EPIC] Generate command

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed-cli#1]
Here is the list of the different provider would be available for the v1:

- [x] Controller (assigned to @Romakita) - merged
- [x] Middleware (assigned to ...)
- [x] Injectable (assigned to ...)
- [x] Model (assigned to ...)
- [x] Decorator (assigned to ...)
- [x] Module (assigned to ...)
- [x] Pipe (assigned to ...)
- [x] Interceptor (assigned to ...)
- [x] Server (assigned to @romakita) - merged

> Note: Add you name on the line

**Comment by Romakita** [comment]
@d0whc3r  I added this epic to dispatch the stories ;). You just have to pick one of the item, add your name, develop the story and create PR  ;)

If you have any question about the project tell me :)
